insert INTO city(cityId,cityName,stateId) values(1,'jabalpur',9)
insert INTO city(cityId,cityName,stateId) values(2,'Indore',9)
insert INTO city(cityId,cityName,stateId) values(3,'Bhopal',9)
insert INTO city(cityId,cityName,stateId) values(4,'Gwalior',9)
insert INTO city(cityId,cityName,stateId) values(5,'Ujjain',9)
insert INTO city(cityId,cityName,stateId) values(6,'Lucknow',11)
insert INTO city(cityId,cityName,stateId) values(7,'Kanpur',11)
insert INTO city(cityId,cityName,stateId ) values(8,'Ghaziabad',11)
insert INTO city(cityId,cityName,stateId) values(9,'Agra',11)
insert INTO city(cityId,cityName,stateId) values(10,'Meerut',11)