server:
  port: 8082
spring:
  datasource:
    password: admin
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: masood.tek.leads@gmail.com
    password: tech2018

# Other properties
    properties:
      mail: 
        smtp: 
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# TLS , port 587
          starttls: 
           enable: true
